blueprint:
  name: Control Velux window and shade with 5-button Lutron Pico
  description: >
    Control a Velux window and shade using a 5-button Lutron Caseta Pico remote.
    - Top button (on): Open window
    - Raise button: Open shade
    - Middle button (stop): Set window to 50% and open shade
    - Lower button: Close shade
    - Bottom button (off): Close window
  domain: automation
  input:
    lutron_device:
      name: Lutron Pico Remote
      description: Select the Lutron Pico remote device
      selector:
        device:
          integration: lutron_caseta
    window_entity:
      name: Velux Window
      description: The window cover entity to control
      selector:
        entity:
          domain: cover
          device_class: window
    shade_entity:
      name: Velux Shade
      description: The shade cover entity to control
      selector:
        entity:
          domain: cover
          device_class: shade

mode: restart
max: 10

trigger:
  - device_id: !input lutron_device
    domain: lutron_caseta
    type: press
    subtype: "on"
    trigger: device
  - device_id: !input lutron_device
    domain: lutron_caseta
    type: press
    subtype: raise
    trigger: device
  - device_id: !input lutron_device
    domain: lutron_caseta
    type: press
    subtype: stop
    trigger: device
  - device_id: !input lutron_device
    domain: lutron_caseta
    type: press
    subtype: lower
    trigger: device
  - device_id: !input lutron_device
    domain: lutron_caseta
    type: press
    subtype: "off"
    trigger: device
  - device_id: !input lutron_device
    domain: lutron_caseta
    type: release
    subtype: "on"
    trigger: device
  - device_id: !input lutron_device
    domain: lutron_caseta
    type: release
    subtype: raise
    trigger: device
  - device_id: !input lutron_device
    domain: lutron_caseta
    type: release
    subtype: stop
    trigger: device
  - device_id: !input lutron_device
    domain: lutron_caseta
    type: release
    subtype: lower
    trigger: device
  - device_id: !input lutron_device
    domain: lutron_caseta
    type: release
    subtype: "off"
    trigger: device

action:
  - choose:
      - conditions:
          - condition: template
            value_template: '{{ trigger.to_state.attributes.action == "press" }}'
        sequence:
          - choose:
              - conditions:
                  - condition: template
                    value_template: '{{ trigger.to_state.attributes.button_number == 2 }}'
                sequence:
                  - service: cover.open_cover
                    target:
                      entity_id: !input window_entity
              - conditions:
                  - condition: template
                    value_template: '{{ trigger.to_state.attributes.button_number == 5 }}'
                sequence:
                  - service: cover.open_cover
                    target:
                      entity_id: !input shade_entity
              - conditions:
                  - condition: template
                    value_template: '{{ trigger.to_state.attributes.button_number == 3 }}'
                sequence:
                  - service: cover.set_cover_position
                    target:
                      entity_id: !input window_entity
                    data:
                      position: 50
                  - service: cover.open_cover
                    target:
                      entity_id: !input shade_entity
              - conditions:
                  - condition: template
                    value_template: '{{ trigger.to_state.attributes.button_number == 6 }}'
                sequence:
                  - service: cover.close_cover
                    target:
                      entity_id: !input shade_entity
              - conditions:
                  - condition: template
                    value_template: '{{ trigger.to_state.attributes.button_number == 4 }}'
                sequence:
                  - service: cover.close_cover
                    target:
                      entity_id: !input window_entity